- name: "[Ubuntu][16] Add repository docker"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: docker
    update_cache: true
  when: input_role_os_distribution_major_version == "16"

- name: "[Ubuntu][18] Add repository docker"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker
    update_cache: true
  when: input_role_os_distribution_major_version == "18"

- name: "[Ubuntu][20] Add repository docker"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker
    update_cache: true
  when: input_role_os_distribution_major_version == "20"