- name: "[CentOS] Ensure old versions of Docker are not installed."
  yum:
    pkg:
      - docker
      - docker-engine
    state: absent

- name: "[CentOS] Install dependencies"
  yum:
    pkg:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: "[CentOS] Add Docker CE repo"
  get_url:
   url: https://download.docker.com/linux/centos/docker-ce.repo
   dest: /etc/yum.repos.d/docker-ce.repo
  when: input_role_os_distribution_major_version | int < 8

- name: "[CentOS] Initial apt upgrade"
  yum:
    name: '*'
    state: latest
    update_cache:  true
  when:
    - input_role_packages_upggrade

- name: "[CentOS] Install docker"
  yum:
    pkg:
      - docker
    state: present
  when: input_role_os_distribution_major_version | int < 8

- name: "[CentOS] Enable and started service docker"
  service:
    name: docker
    state: started
    enabled: yes
  when: input_role_os_distribution_major_version | int < 8

- name: "[CentOS][8] Install podman"
  yum:
    pkg:
      - podman
    state: present
  when: input_role_os_distribution_major_version | int >= 8